### ISSUE TITLE
Slideshow setting for wallpaper

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/cinnamon-control-center#151]
The maximum value for changing the wallpaper is at now 120 minutes. The feature itself is nice, but 2 hours are a needless short time for switching the wallpaper.

Please enhance the time to 24 hours.

Even better: An option to set a different wallpaper at every log in instead of a time interval.

**Comment by JosephMcc** [comment]
I haven't looked in quite some time. The time limit may just be an arbitrary value set for the actual widget. If you change the value in dconf-editor I think it's only limited to the size of an integer.

**Comment by MajidSas** [comment]
I made this pull request:
https://github.com/MajidSas/Cinnamon/compare/master...background-slideshow-delay?quick_pull=1

I changed the maximum value from 120 to 1440 (24 hours). As for changing the background after every log in, this already happens if the slideshow is enabled. I think after every log in the slideshow timer is reseted and a new background is selected.

![screenshot from 2016-09-06 15-25-04](https://cloud.githubusercontent.com/assets/4751632/18273536/618fbb38-7446-11e6-8db4-01d14fab0860.png)

**Comment by Cos-mo** [comment]
> I think after every log in the slideshow timer is reseted and a new background is selected.

That is not the case. I just created a test scenario with LM 18, set the delay to 5 minutes, logged out and back in: I get the same wallpaper as before. Repeating it confirms the result. I also waited for the 5 minutes to ensure, that the slideshow with 5 minutes is working in principle: It is.

The background for the wish to change the wallpaper (only) after login is, that there are days, where my computer gets started very early in the morning, in other case at noon an mostly on different time in between. So a setting via time delay does not exactly do, what I would like to get: A new wallpaper on every day.

Instead of an option to switch the wallpaper at log in, another fine option (as alternative) would be to switch the wallpaper, if the calendar day switches (at 0:00). It would lead to more or less the same result.

**Comment by MajidSas** [comment]
That is strange, because I just logged out and logged back in and the old background was changed immediately after logging in. I tried with different settings. When the slideshow is disabled the background doesn't change after logging in, but it changes every time I log in when it is enabled regardless of the delay I set.

I also use LM18.
