### ISSUE TITLE
Linux Mint 18.0: Wacom Tablet intuos art medium (CTH 690) is not recognized

### ISSUE THREAD

**Issue by JensLinuxMint** [linuxmint/cinnamon-control-center#163]
The wacom tablet intuos art medium (CTH 690) is not recognized by the Cinnamon Controlcenter.
It works in the system (correctly recognized by the kernel 4.4), but it is not recognized in the system control.
This means that the settings of the tablet are only possible via the terminal.

The error has already been fixed in the gnome-control-center. [https://bugzilla.gnome.org/show_bug.cgi?id=746117](url)

Best regards
JensLinuxMint

**Comment by raizercrow** [comment]
I'm using Wacom Intuos CTL-490 and this also happens to me since months ago. I'm on Linux Mint 18.1 and Kernel 4.4.0-62, x86_64.
Following gnome-control-center [bug](https://bugzilla.gnome.org/show_bug.cgi?id=746117), it seems that cinnamon-control-center also won't detect wacom tablets without an eraser. It's fixed in gnome 3.16.

So, this morning I tried `apt-get source cinnamon-control-center`, then modified the source codes inside [panels/wacom](https://github.com/linuxmint/cinnamon-control-center/tree/master/panels/wacom) to match [gnome's](https://git.gnome.org/browse/gnome-control-center/tree/panels/wacom).
Then I built the .deb package, and installed it. It works now.

![wac](https://cloud.githubusercontent.com/assets/17949934/23064846/ff3f1da4-f544-11e6-9b94-18125e338430.png)

Now the Pad button mappings are all messed up, but I guess that's slightly related..

To be specific, the files modified are : 
- [cc-wacom-page.h](https://gist.github.com/raizercrow/be426758ede869665a757b5466cf2e02)
- [cc-wacom-page.c](https://gist.github.com/raizercrow/8903545a31c5887d796c07601a560aa0)
- [cc-wacom-panel.c](https://gist.github.com/raizercrow/bc78a82eb03e4a214bac0728a97079af)
- [test-wacom.c](https://gist.github.com/raizercrow/f7bc93c27c959d706f2736981eb3b805)

With best regards,
raizercrow

**Comment by clefebvre** [comment]
Fixed on git master.
