### ISSUE TITLE
Adopt CSD

### ISSUE THREAD

**Issue by axel358** [linuxmint/cinnamon-control-center#312]
Having a toolbar just to hold a search view  seems unnecessary, the search view and the "All settings" button could be moved to a headerbar instead, just like elementary does

**Comment by axel358** [comment]
![Capture+_2023-05-21-14-40-23](https://github.com/linuxmint/cinnamon-control-center/assets/72220889/281a26f6-6dda-4795-9761-c36a589d25a4)
Couldn't find a decent pic xd

**Comment by leigh123linux** [comment]
cinnamon-control-center isn't used directly, it's used to provide modules for cinnamon-settings.

**Comment by axel358** [comment]
Should I move this request to the Cinnamon repository instead?

**Comment by leigh123linux** [comment]
> Should I move this request to the Cinnamon repository instead?

Why?
There is no interest in using CSD within Mint.

**Comment by axel358** [comment]
Name any new xapp that doesn't use headerbars. N if I read correctly Software is getting one as well

**Comment by leigh123linux** [comment]
> Name any new xapp that doesn't use headerbars. N if I read correctly Software is getting one as well

Ok, try filing the request against cinnamon.

**Comment by fredcw** [comment]
I like this idea. The system settings dialog hasn't changed for a long time and is starting to look a bit tired. It could certainly do with some sprucing up.

btw, sorry about the unfriendly reception you got. I complained about this before: https://github.com/linuxmint/cinnamon-spices-applets/pull/3910 but nobody seems to care. Even though, I think, in the long run allowing this kind of behaviour is detrimental to Mint because it discourages exactly the sort of people that Mint and Cinnamon needs as contributors. The sad thing is that allowing this kind of behaviour is as detrimental to the him as it is to anyone else.

**Comment by Secret-chest** [comment]
> Name any new xapp that doesn't use headerbars. N if I read correctly Software is getting one as well

Wait, where did you read that?

**Comment by fredcw** [comment]
@Secret-chest Software manager will have CSD, it's already done on github.
