### ISSUE TITLE
Please add support for power plans in the Power Management GUI

### ISSUE THREAD

**Issue by leonsk29** [linuxmint/cinnamon-control-center#313]
Linux Mint should implement power plans in the GUI, and it should have at least three modes: High performance, Balanced and Power saving, as Windows and other distros have. I know this exists in the terminal but regular users need a GUI for them to be usable and discoverable by them. Thanks for all your hard work.

**Comment by rcalixte** [comment]
@leonsk29 This feature has already been added as an applet ([link](https://cinnamon-spices.linuxmint.com/applets/view/369)). Are there any missing features or functionality you would like to see implemented?

**Comment by leonsk29** [comment]
Thank you for the tip, but I was suggesting to implement that exact functionality inside the Control Center's Power Management section, not as an applet. I think it's more intuitive that way for users, the majority won't ever notice that the applet exists.

**Comment by rcalixte** [comment]
The obvious challenge is managing dependencies. The functionality is dependent on `power-profiles-daemon` being installed but it can't be set as a dependency of the package due to conflicts with other tools such as auto-cpufreq, tlp, etc. Users will want options and supporting one would require supporting at least a few due to the varied support across vendors and chipsets. If the functionality is built-in, it creates a potential for a mess of dependencies. Considering the size of the team, it is a rather large undertaking for a small reward. I think the best compromise would be communicating the functionality (or applet in this case) for the users who desire such a thing. Many users are not aware or seeking out such options in the first place.

**Comment by leonsk29** [comment]
OK, I see. Thanks.
